


package system.rdf.ui;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JApplet;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.combo.SubstanceComboBoxButton;
import org.jvnet.substance.skin.SkinInfo;
import org.jvnet.substance.theme.ThemeInfo;
import java.util.ArrayList;
import system.rdf.ui.SubstanceSkinComboSelector;
import system.rdf.ui.SubstanceThemeComboSelector;;

/**
 *
 * @author Humberto Rodriguesz Avila
 */
public class UISettingSkin extends javax.swing.JDialog {
	JFrame a;
    /** Creates new form SettingSkin */
    public UISettingSkin(JFrame jFrame) {
        super();
        this.a = jFrame;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	 SubstanceLookAndFeel d = new SubstanceLookAndFeel();
        jToggleButton1 = new javax.swing.JToggleButton();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new SubstanceThemeComboSelector(a, new ArrayList<ThemeInfo>(SubstanceLookAndFeel.getAllThemes().values()).toArray());
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new SubstanceSkinComboSelector(a,new ArrayList<SkinInfo>(SubstanceLookAndFeel.getAllSkins().values()).toArray());
        jButton1 = new javax.swing.JButton();
       

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setting Skin");
        setModal(true);

        jLabel1.setText("Theme");
        jPanel1.add(jLabel1);

        
        jComboBox1.setPreferredSize(new java.awt.Dimension(120, 22));
        jPanel1.add(jComboBox1);

        mainPanel.add(jPanel1);

        jLabel3.setText("Skin");
        jPanel2.add(jLabel3);

        
        jComboBox2.setPreferredSize(new java.awt.Dimension(120, 22));
        jPanel2.add(jComboBox2);

        mainPanel.add(jPanel2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/rdf/resources/home.png"))); // NOI18N
        jButton1.setToolTipText("default look and feel");
        jButton1.setPreferredSize(new java.awt.Dimension(27, 26));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton1);

        getContentPane().add(mainPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
          public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    SwingUtilities.updateComponentTreeUI(getRootPane());
                    SwingUtilities.updateComponentTreeUI(a);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(UISettingSkin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(UISettingSkin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(UISettingSkin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(UISettingSkin.class.getName()).log(Level.SEVERE, null, ex);
                }
          }
        });
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private SubstanceThemeComboSelector jComboBox1;
    private SubstanceSkinComboSelector jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
